logs:
    dir_logs: logs/vqa/mlb_noatt_train
vqa:
    dataset: VQA
    dir: data/vqa
    trainsplit: train
    nans: 2000
    maxlength: 26
    minwcount: 0
    nlp: mcb
    pad: right
    samplingans: True
coco:
    dir: data/coco
    arch: fbresnet152torch
    mode: noatt
model:
    arch: MLBNoAtt
    seq2vec:
        arch: skipthoughts
        dir_st: data/skip-thoughts
        type: BayesianUniSkip
        dropout: 0.25
        fixed_emb: False
    fusion:
        dim_v: 2048
        dim_q: 2400
        dim_h: 1200
        dropout_v: 0.5
        dropout_q: 0.5
        activation_v: tanh
        activation_q: tanh
    classif:
        activation: tanh
        dropout: 0.5
optim:
    lr: 0.0001
    batch_size: 512
    epochs: 100
